project: deblur_gan
experiment_desc: fpn_mobilenet_real

phase: train
warmup_num: 0

# ===== TRAIN CONTROL =====
batch_size: 1
num_epochs: 30
train_batches_per_epoch: 1151
val_batches_per_epoch: 200
image_size: [256, 256]

# ===== DATA =====
train:
  files_a: E:/wagon/DeblurGANv2/dataset/blur/*.png
  files_b: E:/wagon/DeblurGANv2/dataset/sharp/*.png
  size: 256
  crop: random
  scope: geometric
  corrupt:
    - name: motion_blur
    - name: jpeg
    - name: sharpen
  preload: false
  preload_size: 0

val:
  files_a: E:/wagon/DeblurGANv2/dataset/blur/*.png
  files_b: E:/wagon/DeblurGANv2/dataset/sharp/*.png
  size: 256
  crop: center
  scope: geometric
  corrupt: []
  preload: false
  preload_size: 0

# ===== MODEL (NO COMPROMISE) =====
model:
  g_name: fpn_mobilenet
  d_name: patch_gan
  d_layers: 3

  norm_layer: instance
  dropout: false
  blocks: 9
  learn_residual: true

  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: wgan-gp

# ===== OPTIMIZER =====
optimizer:
  name: adam
  lr: 0.00005

# ===== SCHEDULER =====
scheduler:
  name: linear
  start_epoch: 10
  min_lr: 0.0000001
